### ISSUE TITLE
For BDD, add functionality to work with request revoking

### ISSUE THREAD

**Issue by rhudz-ingram** [cloudblue/connect-devops-testing-library#35]
Having this e2e test
```
Scenario: The customer changes trial plan to paid
  Given new asset request
  * request with type "change"
  * request with item "abc"
  When subscription request is processed
  Then request status is "scheduled"
  
  * request is revoked
  When subscription request is processed
  Then request status is "revoked"
```
I would need a step for `request is revoked` and the processing loop that takes into account the `revoking` status,
in addition to the `pending` status (https://github.com/cloudblue/connect-devops-testing-library/blob/master/connect/devops_testing/request.py#L581).

I've created my own step for revoking a request, using a custom API URL/key and sending a raw POST to the request.  
But it would be better to integrate this into the library already having the Connect client prepared.

Thanks.

**Comment by othercodes** [comment]
Closed in #47
